experiment: balls
# model: REDSDS
model: SNLDS
dataset: balls
seg_labels: true
only_segmentation: True
d_min: 20
d_max: 50
# batch_size: 14 # 14 * 3 = 42 ~ 40
batch_size: 40 # for faster training
n_obj: 3
context_length: 100
prediction_length: 0
freq: H
obs_dim: 2
x_dim: 8
log_dir: ./results/exps2-d/balls/{timestamp}/logs/
log_steps: 500
# log_steps: 1
model_dir: ./results/exps2-d/balls/{timestamp}/models/
model_best_dir: ./results/exps2-d/balls/{timestamp}/models/best/
save_steps: 10000
# save_steps: 1
num_categories: 3
num_steps: 120000
# num_steps: 60000
# num_steps: 1
num_samples: 1
# objective: elbov2
objective: elbo
# learning rate 调整
flat_learning_rate: false
warmup_start_lr: 5.e-5
# learning_rate: 0.0002
learning_rate: 0.0004
grad_clip_norm: 10.
weight_decay: 1.e-5
warmup_steps_lr: 2000
# switch temperature 调整
switch_t_annealing: true
switch_t_init: 100.
switch_t_min: 10.
switch_t_annealing_rate: 0.95
switch_t_annealing_steps: 100
switch_t_annealing_kickin_steps: 5000
# entropy 调整
cont_ent_anneal: 1.0
# xent 调整
xent_annealing: true
xent_init: 100.
xent_rate: 0.95
xent_steps: 50
xent_kickin_steps: 2000
# duration temperature
dur_t_annealing: true
dur_t_init: 10.
dur_t_min: 1.
dur_t_annealing_rate: 0.95
dur_t_annealing_steps: 100
dur_t_annealing_kickin_steps: 5000
initial_switch:
  mlp_hiddendim: 8
discrete_transition:
  takes_x: true
  takes_y: false
  takes_hidden_states: false
  no_interaction: false
  interaction_simple: false
  interaction_gnn: true
  interaction_gnn_fully_connected: false
  interaction_gnn_est_edge: true
  interaction_gnn_gt_edge: false
continuous_transition:
  model_type: linear
  tied_cov: false
  trainable_cov: true
  fixed_sigma: 0.02
  max_scale: 2
  mlp_hiddendim: 8
emission:
  model_type: linear
  tied_cov: true
  trainable_cov: true
  fixed_sigma: 0.02
  max_scale: 2
inference: 
  tied_cov: false
  trainable_cov: true
  fixed_sigma: 0.02
  max_scale: 2
  embedder: brnn  # transformer or brnn
# BRNN params
  embedding_rnndim: 16
  embedding_rnnlayers: 1
# Transformer params
  embedding_trans_usepe: true
  embedding_trans_nhead: 1
  embedding_trans_embdim: 4
  embedding_trans_mlpdim: 16
  embedding_trans_nlayers: 1
# Causal RNN
  use_causal_rnn: true
  causal_rnndim: 16
# MLP
  mlp_hiddendim: 32
initial_state:
  tied_cov: true
  trainable_cov: true
  fixed_sigma: 0.02
  max_scale: 2
  mlp_hiddendim: 8
control:
  mlp_hiddendim: 64
  has_ctrl: false
  z: false
  x: false
  inference: false
  emb_dim: 0
  feat_dim: 0
  n_staticfeat: 0
  n_timefeat: 0
transform_target: false
transform_only_scale: false
use_jacobian: false
forecast:
  num_samples: 100
  deterministic_z: true
  deterministic_x: false
  deterministic_y: true